### ISSUE TITLE
SnapTut Deserves a Prettier Aesthetic

### ISSUE THREAD

**Issue by roblevintennis** [ibrierley/SnapTut#1]
@ianscoding please excuse this ridiculous &ldquo;issue&rdquo;, but I'm really meaning to reach out and say, firstly, thanks for this wonderful resource, but secondly, I feel it's not aesthetically living up to the value it provides. Let me explain myself…

I've been actively putting together an SVG animation tutorial and find myself landing back on your dribbles quite frequently on random searches (so SEO does seem to be good!). The official snap.svg intro doesn't go nearly as deep (probably a good thing), and so I think your site does a great job of being a de facto &ldquo;read this after the Getting Started&rdquo; resource. However, it doesn't look to be getting the traction it deserves so far (I've only done some cursory buzzsumo and twitter searches but I'm not seeing a ton of social shares). My take is that it's primarily due to the Internets pickiness for UI.

Some examples:

Here's a CSS layout site, it's starting to be a bit dated, but still a good example of a similarly focused topic with tuts, [CSS Layout](http://learnlayout.com/). When it came out it did quite well from a traction perspective, and I believe it was 60% great content, but 40% that it was pleasing to look at.

Here's a site we did (unicorn-ui) that's getting some nice traction (we also provide some &ldquo;real value&rdquo; with the Buttons code that saves developers tons of time) [Buttons Library](http://unicorn-ui.com/buttons/) and our older [Builder](http://unicorn-ui.com/buttons/builder/) which unfortunately is a bit out of date. 

Apologies for being so long-winded, but my point is that I believe the functionality you already have on your SnapTut dribbles site + a UI reset could make this hugely popular. Are you interested in some collaboration on this? As you probably have empathy and can relate, my time is limited so I couldn't make any definitive promises, but, I AM interested in helping if you're open. lmk

Thanks again for the resource Ian and best of luck either way!

**Comment by roblevintennis** [comment]
Just re-read and definitely don't want to come off as disrespectful, you're obviously doing an amazing job and SEO SERPs are to be commended as well. Hope it's clear that I'm fond of the dribbles site and just see a way it could be even better :wink:

**Comment by ibrierley** [comment]
Heh its an interesting read, I wasn't sure how it was going to pan out! So not seen as disrespectful, no worries on that account, and its always actually really great to get feedback, whatever its form. Long winded reply to follow, hope you don't mind ;).

I've got waylaid slightly from the original intention if I'm totally honest. My original plan was to basically write an animated tutorial in Snap itself (rather than a tutorial on animation),  so more of a journey into Snap, and there would be pan/zooming into certain areas to focus on, telling a story, rather than a flat page which you can edit itself, that was a bit of a side effect, but it has its uses. Then other visually pleasing tutorials in other stuff could be easily written as well.

However, as can be seen, that never transpired, its less of a tutorial than I wanted, and more of just a botch of solutions :). Full time work and time spent focusing on problem solving took over from looking after the site. I haven't updated it in a while and should do (some of it I even consider wrong really)! Maybe this post will be a nudge for a few things. Maybe I'll try and update some of the other stuff I have, but also ponder the visual aspect of the site.

Firstly, SEO Is quite good, and quite interesting to me and happy with. Social media is easy to soak up time unfortunately, so I have left that dangle really, its not great, but I'm not worried there (also interesting that it does quite well irrespective of it, and I have a reasonable handle why I think).

The visual aspect and 'journey' I would like to improve for sure. Initially I also had a primary consideration, that flashy stuff no matter how elegant, should get in the way of usability and learning.

So I guess my main initial question would be, (irrespective of visual aspects) what functionality would be useful, or is it more than it doesn't look modern ? What would help folk the most ? Then ponder the visual side after.

I'm always interesting in collaboration in anything, I actually think thats how things do become more successful, one person alone always gets distracted on another path. Also interested in your svg animation tutorial (I have the odd further bit I want to do there if time permits).

(Interesting you call it a dribbles site btw ;0)

Thanks for the feedback.

Ian

**Comment by roblevintennis** [comment]
^dribbles^dabbles^ _face palm_ :tongue: apologies there

> what functionality would be useful, or is it more than it doesn't look modern ? What would help folk the most ? @ianscoding taking on "functional" and "modern":

**Functional** Currently, you go to `http://svg.dabbles.info/`, click one of the left hand links which takes you to a separate page where the example is presented. If I'd like to see another example, I have to click back button, to get back to the list. That's a poor UX. I think there's a big win to be had by using a "vertical master detail" layout where you have a sidebar to the left (much like the bullet list you have, but imagine a sidebar that remains fixed where each rectangular section/link acts as a link to a new detail page; ex. linking from snaptut-parse.html to snaptut-title.html, etc., would all be controlled from the master sidebar but it appears as though you're staying on one page).

Here's a description of what I'm calling master detail (and the site itself seems to be implemented as a master detail too): [master detail example](http://www.oracle.com/webfolder/ux/middleware/alta/patterns/MasterDetail.html)
This has some examples of master detail too:
http://uxmag.com/articles/rich-internet-application-screen-design

I might also add a simple previous/next pagination additionally so that user could also &ldquo;page through&rdquo; quickly should they choose to.

**Modern** Yes, I do think that "doesn't look modern" is, in fact, an issue, but more importantly, that a basic use of solid design (contrast, alignment, proximity, etc.) would just make the site more "enchanting" and thus usable.

**Comment by ibrierley** [comment]
I think that makes perfect sense, I'll definitely have a ponder. I have 
a couple of thoughts, might be the holidays before I get much time though.

Appreciate the concise feedback.

Ian

**Comment by roblevintennis** [comment]
@ianscoding sure thing. If I get a moment I'll try to help...but sounds like you might want to tackle this yourself :)

**Comment by ibrierley** [comment]
Feel free to ping me offline btw rather than github, ians.coding@gmail.com

I always like to have a bash at stuff, but I'm happy to learn from 
others who know stuff better :).

Ian

**Comment by roblevintennis** [comment]
@ianscoding sure thing .. makes sense. Thanks again for the resource and the time you've put in Ian ;-)

**Comment by ibrierley** [comment]
I've done a couple of updates, so menu is on there, I need to redo it all properly one day though!

Menu should be on every page. I need to make the menu a bit sexier some point, and there's a couple of ickle css bugs on there and a couple of the other pages, that I'll try and sort, but it may help for the moment.

Happy to take on board visual suggestions on improving that menu. The staying on one page thing (I guess I'm thinking more along the lines of single page apps), I'm probably going to leave for the moment, I'm not quite happy with the change SEO wise, and I think I'd need to learn a few other bits (which I'm happy to do, but probably for another day).

I need to strip some redundant pages out as well at some point.

**Comment by roblevintennis** [comment]
> staying on one page thing (I guess I'm thinking more along the lines of single page apps), I'm probably going to leave for the moment, I'm not quite happy with the change SEO

Understandable, and my intention probably got lost in translation: &ldquo;**appears** as though you're staying on one page&rdquo; .. so it could, in fact, reload page, but the user would feel as though they were using a master/detail.

But I had a look at the latest live site and you've actually implemented (functionally) what I suggested and I think it's an improvement. It's a bit better aesthetically, but I would say could still use much polish; I figure you plan to do this "over time"...all said, I'd say you've mostly addressed the biggest UX issue I had so I'll go ahead and close the ticket.

Thanks @ianscoding and good luck on this project! Gonna close this for you...let's stay in touch! Cheers
